const COLORS = {
  GREY_DARK: '#4D5254',
  GREY_LESS_DARK: '#777',
  GREY_MID: '#E7E7E7',
  GREY_LIGHT: '#E7E7E7',
  GREY_BRIGHT: '#FAFAFA',
  WHITE: '#FFFFFF',

  BLUE: '#B0C4EC',
};

export default COLORS;
